# Generated by Django 4.1.6 on 2023-09-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_iteminventory_alter_user_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Beauty & Skin Care', 'Beauty & Skin Care'), ('Clothing', 'Clothing'), ('Home & Kitchen', 'Home & Kitchen'), ('Accessories', 'Accessories')], max_length=100),
        ),
    ]
