# Generated by Django 4.1.5 on 2023-11-05 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_item_description_alter_item_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='items',
        ),
        migrations.AddField(
            model_name='iteminventory',
            name='user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
